name: Kodomon Test
favicon: null
layout_spectrum: 0.60056
typography_spectrum: 0.55461
title: Kodomon Karate-Do
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#d1973c'
    - '#976f33'
    - '#939495'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
